name = "sub"
main = "src/worker.ts"
compatibility_date = "2024-09-18"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "${KV_NAME}" }
]

# Add this type field
type = "javascript"
